# from enum import Enum, StrEnum

class cmds:
    start = 'start'
    rules = 'rules'
    help = 'help'
    change_name = 'change_name'
    change_lang = 'change_lang'
    new = 'new'
    join = 'join'
    repeat = 'repeat'
    repeat_id = 'repeat {}'
    main_menu = 'main_menu'
    leave = 'leave'
    set_points = 'set_points'
    set_money = 'set_money'
    show_joined = 'show_joined'
    play = 'play'
    abort = 'abort'
    unexpected = 'unexpected'
    unknown = 'unknown'
